### ISSUE TITLE
App won't download on Nexus Tablet from Google Play Store

### ISSUE THREAD

**Issue by pigottlaura** [wishiwashere/TeamProject-2016#2]
sketch_160118_a_testingCameraKetai-release-signed.apk will not download to the College Nexus tablets. "Designed for phones. Your device isn't compatible with this version" appears when you go to the app's page on Google Play Store.

**Comment by pigottlaura** [comment]
Note - As far as I can tell, the "Designed for phones" message on the app's Play Store page is not part of the issue, it is just a message which appears if an app doesn't meet all specifications of Google Play's expectations for tablet apps. I don't think it actually stops someone from downloading the app, it just lets them know that it may not have been designed specifically for a tablet.
As far as the "Your device isn't compatible with this version" message (which is stopping us from downloading the app onto the Nexus tablets) I have a theory that this issue lies in the AndroidManifest.xml file and not in the app's code.

**Comment by pigottlaura** [comment]
This is still an ongoing issue, and one that we have been looking at how to resolve since week one. Currently, the Google Nexus 7 is the only device we have found which does not allow our app to be downloaded from the [Google Play Store](https://play.google.com/store/apps/details?id=processing.test.wish_i_was_here)

**Comment by eirenmc** [comment]
This issues has now been RESOLVED !!! :) Successful bug fix for Google Nexus 7 (camera permission requested, but now only a front camera is required). We found that the permission camera refers to the back camera and we need to refer to the front camera in order for the nexus tablets avail of the app in the play store

**Comment by pigottlaura** [comment]
It seems as if the use-permission "CAMERA" implicitly inferred <use-feature> for both "CAMERA" (back camera) and "CAMERA.FRONT" (front camera). Delighted it is now fixed :)
